# 
___
___
## ╭────────────────── Traceback (most recent call last) ───────────────────╮│ c:\pythonLearn\widgets.py:89 in on_button_pressed                      ││                                                                        ││    86 │   │   │   else:                                                ││    87 │   │   │   │   task=asyncio.create_task(delete_note(self.delete ││    88 │   │   │   app.Screen_my.remove_pane(app.Screen_my.active)      ││ ❱  89 │   │   │   await task                                           ││    90 │   │   if event.button.id.startswith("ankimake_"):              ││    91 │   │   │   anki_make(card.name)                                 ││    92 │   │   │   card.remove()                                        ││                                                                        ││ ╭──────────── locals ─────────────╮                                    ││ │ event = Pressed()               │                                    ││ │  self = Screen_anki(id='anki1') │                                    ││ ╰─────────────────────────────────╯                                    │╰────────────────────────────────────────────────────────────────────────╯UnboundLocalError: cannot access local variable 'task' where it is not 
associated with a value
___
## 
### 错误分析
- 

#### [Traceback](https://zh.wikipedia.org/wiki/Traceback)
你遇到了一个[UnboundLocalError](https://zh.wikipedia.org/wiki/UnboundLocalError)，这意味着你试图在[变量](https://zh.wikipedia.org/wiki/变量)被赋值之前访问它。

#### [代码](https://zh.wikipedia.org/wiki/代码)分析
在你的[代码](https://zh.wikipedia.org/wiki/代码)中，第89行试图`await task`，但在某些情况下，[变量](https://zh.wikipedia.org/wiki/变量)`task`可能没有被赋值。

#### 解决方案
你需要确保在所有情况下，[变量](https://zh.wikipedia.org/wiki/变量)`task`都被赋值。可以通过在赋值前初始化[变量](https://zh.wikipedia.org/wiki/变量)来解决这个问题。

```python
task = None
if some_condition:
    task = asyncio.create_task(delete_note)
    await task
```


### 
___
